kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-pdfgen
  namespace: amt
  labels:
    team: amt
spec:
  image: {{image}}
  port: 8080
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/is_alive
    initialDelay: 20
  liveness:
    path: /internal/is_alive
    initialDelay: 20
  startup:
    path: /internal/is_alive
    initialDelay: 30
    failureThreshold: 45
    periodSeconds: 5
  replicas:
    disableAutoScaling: true
    min: 1
    max: 1
  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      memory: 1024Mi
  accessPolicy:
    inbound:
      rules:
        - application: amt-distribusjon
